### ISSUE TITLE
consider using grpc instead of rest

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/sciencemesh-nextcloud#15]
In the light of https://github.com/cs3org/reva/issues/1813 it would be nice if our nextcloud storage driver for reva could become a generic cs3-storage driver.
But grpc server-side is not available for php yet, so that's not feasible yet unfortunately.
we'll keep it as ad-hoc rest until then, it's not such a big difference in the end.

**Comment by ylebre** [comment]
See also: https://grpc.io/docs/languages/php/basics/
