### ISSUE TITLE
storage controller in nextcloud app, one route per method

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/sciencemesh-nextcloud#16]
For each method in
https://github.com/cs3org/reva/blob/master/pkg/storage/storage.go#L31-L59
create a route for each one, for instance something like http://nc/apps/sciencemesh/reva/@einstein/GetMD

**Comment by michielbdejong** [comment]
@ylebre now seeing these arrive in the nextcloud logs:
```sh
172.26.0.3 - - [25/Jun/2021:14:51:40 +0000] "POST /apps/sciencemesh/~alice/CreateHome HTTP/1.1" 302 1483 "-" "Go-http-client/1.1"
172.26.0.3 - - [25/Jun/2021:14:51:41 +0000] "GET /login HTTP/1.1" 200 5088 "http://nc/apps/sciencemesh/~alice/CreateHome" "Go-http-client/1.1"
172.26.0.3 - - [25/Jun/2021:14:51:47 +0000] "POST /apps/sciencemesh/~alice/ListFolder HTTP/1.1" 302 1483 "-" "Go-http-client/1.1"
172.26.0.3 - - [25/Jun/2021:14:51:47 +0000] "GET /login HTTP/1.1" 200 5092 "http://nc/apps/sciencemesh/~alice/ListFolder" "Go-http-client/1.1"
172.26.0.3 - - [25/Jun/2021:14:51:47 +0000] "POST /apps/sciencemesh/~alice/InitiateUpload HTTP/1.1" 302 1485 "-" "Go-http-client/1.1"
172.26.0.3 - - [25/Jun/2021:14:51:47 +0000] "GET /login HTTP/1.1" 200 5089 "http://nc/apps/sciencemesh/~alice/InitiateUpload" "Go-http-client/1.1"
172.26.0.3 - - [25/Jun/2021:14:51:48 +0000] "PUT /apps/sciencemesh/~alice/Upload/test.txt HTTP/1.1" 302 1483 "-" "Go-http-client/1.1"
172.26.0.3 - - [25/Jun/2021:14:51:48 +0000] "GET /login HTTP/1.1" 200 5086 "http://nc/apps/sciencemesh/~alice/Upload/test.txt" "Go-http-client/1.1"
```

The `GET /login` ones are probably because the `POST /apps/sciencemesh/~alice/...` ones are unauthenticated, and get redirected to the login page

**Comment by michielbdejong** [comment]
@ylebre which URL should reva hit on nextcloud? In https://github.com/pondersource/sciencemesh-nextcloud/issues/16 I used the format `/apps/sciencemesh/~alice/ListFolder` so far (if ListFolder is the exact name of the method being called in our reva storage driver https://github.com/cs3org/reva/blob/master/pkg/storage/storage.go#L38)

**Comment by michielbdejong** [comment]
See https://github.com/michielbdejong/reva/blob/nextcloud-storage-driver/pkg/storage/fs/nextcloud/nextcloud_server_mock.go for the routes. They're all POST for now, but in the future we'll switch some of them to GET (see #18).

**Comment by ylebre** [comment]
Routes for each method are now available in the nextcloud app under /~alice/api/{method}
