### ISSUE TITLE
Failure to use usernames containing @, as shareOwner or shareWith

### ISSUE THREAD

**Issue by mirekys** [pondersource/sciencemesh-nextcloud#178]
Hi,

in OC10 (& most probably NC), it is possible to have users with usernames in the e-mail like format: `joe@example.org`.
(we have quite a lot of such users on our production instance)

These users cannot be currently shared with or from using sciencemesh sharing flow.

Their federated sciencemesh id looks like  `joe@example.org@sciencemesh.cesnet.cz`,
but the current implementation seems to use `example.org` part as their sciencemesh site to be contacted,
which ultimately fails:

https://github.com/pondersource/oc-sciencemesh/blob/4d924aaf4f3a6be7621c1a52dd98603da9d943c0/lib/Controller/RevaController.php#L232-L299

**Comment by michielbdejong** [comment]
Thanks for raising this! Should be pretty easy to fix.

**Comment by MahdiBaghbani** [comment]
fixed in release v0.4.3 https://github.com/pondersource/nc-sciencemesh/pull/360 https://github.com/pondersource/nc-sciencemesh/pull/361.

details in this issue https://github.com/pondersource/nc-sciencemesh/issues/272
