### ISSUE TITLE
undefined array key "resourceId" when receiving share in NC

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/sciencemesh-nextcloud#214]
```
{"reqId":"KiSXH16jy8FOgwTTwV0O","level":3,"time":"2023-06-13T12:40:39+00:00","remoteAddr":"167.99.80.220","user":"--","app":"PHP","method":"POST","url":"/index.php/apps/sciencemesh/~einstein/api/ocm/addReceivedShare","message":"Undefined array key \"resourceId\" at /var/www/html/apps/sciencemesh/lib/Controller/OcmController.php#491","userAgent":"Go-http-client/1.1","version":"26.0.0.6","data":{"app":"PHP"}}
{"reqId":"KiSXH16jy8FOgwTTwV0O","level":3,"time":"2023-06-13T12:40:39+00:00","remoteAddr":"167.99.80.220","user":"--","app":"PHP","method":"POST","url":"/index.php/apps/sciencemesh/~einstein/api/ocm/addReceivedShare","message":"Trying to access array offset on value of type null at /var/www/html/apps/sciencemesh/lib/Controller/OcmController.php#491","userAgent":"Go-http-client/1.1","version":"26.0.0.6","data":{"app":"PHP"}}
```

**Comment by MahdiBaghbani** [comment]
`resourceId` doesn't exist on line 491 of the OcmController in Nextcloud app.

https://github.com/pondersource/nc-sciencemesh/blob/37c828f67527ae51470f01dbbc4bd86328fb5f38/lib/Controller/OcmController.php#LL491C24-L491C24 

This issue has been fixed on 
https://github.com/pondersource/nc-sciencemesh/pull/346
https://github.com/pondersource/nc-sciencemesh/pull/344

Can you check the branch that runs into this error? and see if it is `nextcloud` or `nextcloud-dev`?

**Comment by MahdiBaghbani** [comment]
![Screenshot from 2023-06-13 20-21-22](https://github.com/pondersource/sciencemesh-php/assets/13681688/4ccade3d-8c89-4531-8afd-255c60b51b97)

It has been solved, the wrong branch was the case for this issue.
