### ISSUE TITLE
generate-invite endpoint at reva

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/sciencemesh-nextcloud#54]

**Comment by ishifoev** [comment]
@michielbdejong Yeah we have a problem with endpoint in reva with generate-invite. We don't have a configurable endpoint for now we can do some hard-code directly from reva. I see docs that our curl command can be something like this
```curl -d'{"opaque": "map": {"key": "123", "value": "123"}}' -H 'Content-Type: application/json' -i http://einstein:relativity@localhost/index.php/apps/sciencemesh/~einstein/api/ocm/GenerateInviteToken```

**Comment by michielbdejong** [comment]
Implemented it just now in https://github.com/michielbdejong/reva/commit/9427b77432950ff78fe19db1bad32f9bde2f7da8
This is how it works now:
```sh
root@e1e804cafb73:/var/www/html# curl -i https://einstein:relativity@revanc1.docker/invites/generate
HTTP/2 200 
content-type: application/json
vary: Origin
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNjM4MDI1MDExLCJpYXQiOjE2Mzc5Mzg2MTEsImlzcyI6InNvbWUtaWRwIiwidXNlciI6eyJpZCI6eyJpZHAiOiJzb21lLWlkcCIsIm9wYXF1ZV9pZCI6ImVpbnN0ZWluIiwidHlwZSI6MX19LCJzY29wZSI6eyJ1c2VyIjp7InJlc291cmNlIjp7ImRlY29kZXIiOiJqc29uIiwidmFsdWUiOiJleUp5WlhOdmRYSmpaVjlwWkNJNmV5SnpkRzl5WVdkbFgybGtJam9pYzNSdmNtRm5aUzFwWkNJc0ltOXdZWEYxWlY5cFpDSTZJbTl3WVhGMVpTMXBaQ0o5TENKd1lYUm9Jam9pYzI5dFpTOW1hV3hsTDNCaGRHZ3VkSGgwSW4wPSJ9LCJyb2xlIjoxfX19.rAnhEfU7cRiyg5AWZ59KV8h0adk8Z-MCR9doXwRe1fI
content-length: 342
date: Fri, 26 Nov 2021 14:56:52 GMT

{
   "status": {
      "code": 1,
      "trace": "00000000000000000000000000000000"
   },
   "invite_token": {
      "token": "161405dd-05f0-4806-8b42-1482b3185c63",
      "user_id": {
         "idp": "some-idp",
         "opaque_id": "einstein",
         "type": 1
      },
      "expiration": {
         "seconds": 1638025012
      }
   }
}
```

**Comment by michielbdejong** [comment]
So from there you need to take `responseBodyObject["invite_token"]["token"]`, that's to say `"161405dd-05f0-4806-8b42-1482b3185c63"`.

**Comment by ishifoev** [comment]
I think if you are take ```curl -i http://einstein:relativity@0.0.0.0:17001/invites/generate``` you are take 404 not found

**Comment by ishifoev** [comment]
if you are try ```curl -i http://einstein:relativity@0.0.0.0:17001/ocm/invites/generate``` you are take 401 authorized required.
