### ISSUE TITLE
Clarify iopUrl

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/sciencemesh-nextcloud#61]
Reading https://sciencemesh-nextcloud.readthedocs.io/en/latest/admin.html#admin-documentation it's very unclear how exactly you have to set the iopUrl settings.
Looking at https://github.com/cs3org/ocm-test-suite/blame/revanc/run.sh#L16 you can see that it can be done with:
```sql
insert into oc_appconfig (appid, configkey, configvalue) values ('sciencemesh', 'iopUrl', 'https://revanc1.docker/');
```

If reva is on localhost you need to point it to `http://localhost:<http-port-from-your-revad.toml>:`

@navid-dada sorry you ran into this, can you fix this lack of documentation  in the source of that readthedocs site, [here](https://github.com/pondersource/sciencemesh-nextcloud/blame/main/source/admin.rst#L3)?

**Comment by navid-dada** [comment]
yes, We will do it.
