### ISSUE TITLE
Make docs mention both NC and OC-10

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/sciencemesh-nextcloud#69]
Look at https://github.com/pondersource/sciencemesh-nextcloud/blob/main/source/installation.rst#install-the-sciencemesh-app - it only mentions pondersource/nc-sciencemesh, not pondersource/oc-sciencemesh.

Also, the latest code to use of both should be the default branches, probably?

**Comment by michielbdejong** [comment]
Also https://github.com/cs3m4eosc-wp2/sciencemesh/edit/master/docs/content/en/docs/How%20to%20join%20ScienceMesh/_index.md

**Comment by michielbdejong** [comment]
@navid-dada is collecting improvements and will update as soon as he finishes the work on Kubernetes

**Comment by navid-dada** [comment]
I push my changes to the repo and it is updated and there are two separate doc about oc10 and nc
