### ISSUE TITLE
404 error on  http://mesh.pondersource.org/iop/invites/generate

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/sciencemesh-nextcloud#71]
Continued here from https://gitter.im/sciencemesh/task-force-technical?at=630c66a9b16e8236e34f3076

**Comment by michielbdejong** [comment]
And also discussion in https://pondersource.slack.com/archives/C021TEKS1J7/p1661719423039399

**Comment by navid-dada** [comment]
it is the final state so far: 
when I am calling `/invites/generate`, the `authentication` and `create home` endpoint on nextcloud will be called but the final result is error 404 without any response body, whereas I searched in the Reva code and all NotFond (404) responses have response message.

when I am calling `/invites/generate`, the `authentication` and `create home` endpoint on nextcloud will be called but the final result is error 401.

**Comment by michielbdejong** [comment]
Do you mean `/ocm/invites/generate` the second time?
And what do you see in the Nextcloud logs for the Authenticate call in that case?
Remember we changed the shared secret on cloud.pondersource.org last week, did you change that back yet?

The 404 probably means route-not-found, you can test this assumption by trying what the behaviour is for a route that we know to be wrong, e.g. by hitting `/some/garbage` and seeing whether the behaviour differs from that for `/invites/generate`.

The 401 probably means either the username is not found or the shared secret is wrong.

**Comment by navid-dada** [comment]
so yes the second one was OCM and I edit my description. so changing the route I think won't help because my API call triggers the Reva to nc/oc APIs and this shows I am accessing the write address. and my request entered Reva core. and as you can see there in the end of Reva log during the API call last warning has some 404 results.

> 2022-08-29 18:52:38.28 INF src/github/cs3org/reva/internal/http/interceptors/auth/auth.go:258 > core access token generated pid=1 pkg=rhttp traceid=0490d565041ae25623aca049b2546abe

> 2022-08-29 18:52:38.28 INF src/github/cs3org/reva/internal/http/interceptors/providerauthorizer/providerauthorizer.go:83 > skipping provider authorizer check for: /invites/generate pid=1 pkg=rhttp traceid=0490d565041ae25623aca049b2546abe

> 2022-08-29 18:52:38.28 DBG src/github/cs3org/reva/pkg/rhttp/rhttp.go:255 > http routing: head=invites tail=/generate svc=not-found pid=1 pkg=rhttp

> 2022-08-29 18:52:38.28 WRN src/github/cs3org/reva/internal/http/interceptors/log/log.go:112 > http end="29/Aug/2022:18:52:38 +0000" host=10.1.86.241 method=POST pid=1 pkg=rhttp proto=HTTP/1.1 size=0 start="29/Aug/2022:18:52:37 +0000" status=404 time_ns=335132132 traceid=0490d565041ae25623aca049b2546abe uri=/invites/generate url=/invites/generate

**Comment by michielbdejong** [comment]
> > you can test this assumption

> changing the route I think won't help

Still, it's better to try it out in practice than inside our heads! :)

And
> what do you see in the Nextcloud logs for the Authenticate call

Did you look into this?

I'm at a camp site where the internet is very slow but I'll try to see what I can find out from here.

**Comment by michielbdejong** [comment]
I tried out
`update oc_appconfig set configvalue = 'http://mesh.pondersource.org/iop/ocm/' where configkey='iopUrl' and appid='sciencemesh';` 
and
`update oc_appconfig set configvalue = 'http://mesh.pondersource.org/iop/garbage/' where configkey='iopUrl' and appid='sciencemesh';`
and then hitting '+' in the GUI on https://cloud.pondersource.org/index.php/apps/sciencemesh/generate while logged in as einstein.

For iopUrl http://mesh.pondersource.org/iop/garbage/ I see (removed irrelevant parts):
```
nc.do req https://cloud.pondersource.org/index.php/apps/sciencemesh/~einstein/api/storage/CreateHome  pid=1 pkg=rgrpc
nc.do res https://cloud.pondersource.org/index.php/apps/sciencemesh/~einstein/api/storage/CreateHome "OK" pid=1 pkg=rgrpc
http routing: head=garbage tail=/invites/generate svc=not-found pid=1 pkg=rhttp
```

For iopUrl http://mesh.pondersource.org/iop/ocm/ I also see CreateHome, but then:
```
2022-09-01 05:17:47.372 ERR src/github/cs3org/reva/internal/http/interceptors/providerauthorizer/providerauthorizer.go:103 > provider not registered in OCM error="error: not found: mesh.pondersource.org" pid=1 pkg=rhttp
```

**Comment by michielbdejong** [comment]
When I change the loopback secret on cloud.pondersource.org I see 'authsvc: error in Authenticate: Username/password not recognized by Nextcloud backend' so looks like that is correct as it is.

**Comment by michielbdejong** [comment]
Now hitting https://github.com/cs3org/reva/blob/v1.19.0/internal/http/interceptors/providerauthorizer/providerauthorizer.go#L103

I see some uncommitted changes in /root/charts/revad so that's probably what we're working from, right?

I see ocm-providers.json in values.yaml there, and it does seem to include mesh.pondersource.org, not sure why the providerauthorizer is rejecting it.

**Comment by michielbdejong** [comment]
We could try setting the ocm provider authorizer to 'open'

**Comment by michielbdejong** [comment]
That works around it! :)
We'll have to set it to mentix at some point, but for now let's leave it as 'open'

**Comment by michielbdejong** [comment]
I was now able to generate an invite token:
<img width="627" alt="Screenshot 2022-09-01 at 08 14 51" src="https://user-images.githubusercontent.com/408412/187844711-e67ec003-3e13-4ae2-8382-0b9c87cb3607.png">
