### ISSUE TITLE
Write documentation for revad.toml

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/sciencemesh-nextcloud#73]
Various sections, what they mean and do, how to edit them to achieve various results

**Comment by michielbdejong** [comment]
Reva should be a black box to sysadmins, but it's not. You can currently only use it and configure it if you know how to debug the code.

**Comment by david-antos** [comment]
Opened as https://github.com/cs3org/reva/issues/3276

**Comment by michielbdejong** [comment]
Thanks, yes, the two issues make exactly the same point! Closing this one as a duplicate and also as being in the wrong repo. :)
