### ISSUE TITLE
Remove reva https config from chart

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/sciencemesh-nextcloud#81]
See https://github.com/pondersource/sciencemesh-nextcloud/issues/80#issuecomment-1236889821

**Comment by michielbdejong** [comment]
https://github.com/pondersource/charts/blob/addbdb4/revad/values.yaml#L241-L243 and also change the port number from 443 to whatever the ingress expects it to be (port 80?)

**Comment by navid-dada** [comment]
this issue has been closed with this [commit](https://github.com/pondersource/charts/commit/58b2341f81fb54315becb70c9715607381dc16fa)
